### ISSUE TITLE
Failed to run on Mac 

### ISSUE THREAD

**Issue by bayareahank** [vfarcic/jenkins-docker-ansible#4]
I tried to run the whole thing on Mac, and it reports failure. Basically ansible reports an error while doing the registry task. While I checked, it looks the docker-registry project is deprecated and is replaced by docker distribution. Not sure this is directly related. Here is the failure info: 

TASK [registry : Container is running] *****************************************
task path: /vagrant/ansible/roles/registry/tasks/main.yml:7
ESTABLISH LOCAL CONNECTION FOR USER: vagrant
127.0.0.1 EXEC /bin/sh -c '( umask 22 && mkdir -p "`echo $HOME/.ansible/tmp/ansible-tmp-1459984703.87-121680208559373`" && echo "`echo $HOME/.ansible/tmp/ansible-tmp-1459984703.87-121680208559373`" )'
127.0.0.1 PUT /tmp/tmpQB6MwI TO /home/vagrant/.ansible/tmp/ansible-tmp-1459984703.87-121680208559373/docker
127.0.0.1 EXEC /bin/sh -c 'sudo -H -S -n -u root /bin/sh -c '"'"'echo BECOME-SUCCESS-qhwrdkmbhztjojomywdzfcrysgszqyzz; /bin/sh -c '"'"'"'"'"'"'"'"'LANG=en_US.UTF-8 LC_ALL=en_US.UTF-8 LC_MESSAGES=en_US.UTF-8 /usr/bin/python /home/vagrant/.ansible/tmp/ansible-tmp-1459984703.87-121680208559373/docker; rm -rf "/home/vagrant/.ansible/tmp/ansible-tmp-1459984703.87-121680208559373/" > /dev/null 2>&1'"'"'"'"'"'"'"'"''"'"''
An exception occurred during task execution. The full traceback is:
Traceback (most recent call last):
  File "/home/vagrant/.ansible/tmp/ansible-tmp-1459984703.87-121680208559373/docker", line 3728, in <module>
    main()
  File "/home/vagrant/.ansible/tmp/ansible-tmp-1459984703.87-121680208559373/docker", line 1738, in main
    started(manager, containers, count, name)
  File "/home/vagrant/.ansible/tmp/ansible-tmp-1459984703.87-121680208559373/docker", line 1580, in started
    created = manager.create_containers(delta)
  File "/home/vagrant/.ansible/tmp/ansible-tmp-1459984703.87-121680208559373/docker", line 1454, in create_containers
    params['host_config']['Memory'] = mem_limit
KeyError: 'host_config'

fatal: [localhost]: FAILED! => {"changed": false, "failed": true, "invocation": {"module_name": "docker"}, "parsed": false}

NO MORE HOSTS LEFT *************************************************************
    to retry, use: --limit @/vagrant/ansible/cd.retry

PLAY RECAP *********************************************************************
localhost                  : ok=9    changed=0    unreachable=0    failed=1

**Comment by bayareahank** [comment]
Checked against source, found my ansible is 2.0.1.0, while boostrap.sh specifies 1.9.2. Changed to 1.9.2, goes passed the container is running task. Now we see jenkins | Reload task failure: 

TASK: [jenkins | Reload] *****************************************************\* 
==> cd: failed: [localhost] => {"failed": true}
==> cd: msg: Socket error: [Errno 111] Connection refused to http://localhost:8080/reload
==> cd: ...ignoring

Still, since docker-registry deprecated, should we change to docker distribution, as recommended?

**Comment by vfarcic** [comment]
I just re-run it using the same instructions as in the article and it worked. From what I understood, you tried to run the playbook outside of the VM created in the article and run into problems. The first one was caused by not using the same Ansible version (quite a lot of things changed in Ansible 2). A few things would need to be changed in the code to make it Ansible 2 compatible.

I'm not sure why the Jenkins reload returned connection refused. It works when it runs inside the VM set up through the article. My guess is that you are not running it on localhost.

As for Registry, it is not deprecated. It is actively developed. Docker Distribution uses the same Registry and adds few things on top of it. However, the code should be updated to use Registry 2 (latest points to the older version).

In any case, the code should be modified to support Ansible 2, the latest Registry, and few other things. Would you like to give it a try and create a pull request (I can help if you get stuck)? If not, I'll try to find a bit of time and go through it the next weekend.

**Comment by bayareahank** [comment]
Hi Victor, 

Thank you for your prompt response. 

I followed your article to the docker-registry project, which has this line at its page: "This is **DEPRECATED**! Please go to https://github.com/docker/distribution". So we are using docker-distribution now in the current code, not docker-registry any more? 

I run the whole thing by "vagrant up cd --provision", of all the logs, I think there are a few messages may be related to the final Jenkins reload error, here they are: 

==> cd: Running provisioner: shell...
    cd: Running: inline script
==> cd: stdin: is not a tty
==> cd:  [WARNING]: provided hosts list is empty, only localhost is available

==> cd: TASK: [docker | Docker service is restarted] *********************************\* 
==> cd: skipping: [localhost]

It looks the Jenkins reload task is attempting to talk to http://localhost at port 8080, yet as I checked, there is nothing listening at that port. 

As I am still not familiar with the softwares involved, let me dig into it a bit and get back to you.

**Comment by vfarcic** [comment]
Hi,

I misunderstood your first email. The GitHub project docker/docker-registry
is indeed deprecated. However, the container we're using from Docker Hub (
https://hub.docker.com/r/_/registry/) is not deprecated and is part of
Distribution that adds things on top of it. Eventually, Distribution will
take over completely but, at this moment, Docker is still trying to figure
out the roadmap. Most of the things added to Distribution on top of
Registry are experimental and unstable. What I want to say is that there is
not much difference between the two at this moment. Registry (alone or as
part of Distribution) is the main product. We're yet to see what'll come
out of it.

As for Jenkins, since it is running on port 8080 and Ansible playbook is
executed on the same machine, localhost:8080 is valid and should work.
Jenkins does have a problem that it does not respond with status 200 on
requests so I made the Ansible task that reloads it ignore the response.
However, that does not explain the "Connection refused" output you sent me.
Can you send me the complete output from Ansible? Also, it would be great
if you use "-vvvv" when running it. It will execute Ansible in verbose mode
and provide much more detailed output.

On Mon, Apr 11, 2016 at 10:02 PM bayareahank notifications@github.com
wrote:

> Hi Victor,
> 
> Thank you for your prompt response.
> 
> I followed your article to the docker-registry project, which has this
> line at its page: "This is _DEPRECATED_! Please go to
> https://github.com/docker/distribution". So we are using
> docker-distribution now in the current code, not docker-registry any more?
> 
> I run the whole thing by "vagrant up cd --provision", of all the logs, I
> think there are a few messages may be related to the final Jenkins reload
> error, here they are:
> 
> ==> cd: Running provisioner: shell...
> cd: Running: inline script
> ==> cd: stdin: is not a tty
> ==> cd: [WARNING]: provided hosts list is empty, only localhost is
> available
> 
> ==> cd: TASK: [docker | Docker service is restarted]
> 
> ---
> 
> ==> cd: skipping: [localhost]
> 
> It looks the Jenkins reload task is attempting to talk to http://localhost
> at port 8080, yet as I checked, there is nothing listening at that port.
> 
> As I am still not familiar with the softwares involved, let me dig into it
> a bit and get back to you.
> 
> —
> You are receiving this because you commented.
> 
> Reply to this email directly or view it on GitHub
> https://github.com/vfarcic/jenkins-docker-ansible/issues/4#issuecomment-208531702
> 
> ## 
> 
> Viktor Farcic

Blog:
TechnologyConversations.com

Books:
The DevOps 2.0 Toolkit (http://www.amazon.com/dp/B01BJ4V66M or
https://leanpub.com/the-devops-2-toolkit)
Test-Driven Java Development (
http://www.amazon.com/Test-Driven-Java-Development-Viktor-Farcic-ebook/dp/B00YSIM3SC
)

**Comment by bayareahank** [comment]
It still failed after re-run, but gave a different error msg. Also still nothing listening on port 8080. 

Active Internet connections (only servers)
Proto Recv-Q Send-Q Local Address           Foreign Address         State  
tcp        0      0 0.0.0.0:54575           0.0.0.0:\*               LISTEN  
tcp        0      0 0.0.0.0:111             0.0.0.0:\*               LISTEN  
tcp        0      0 0.0.0.0:22              0.0.0.0:\*               LISTEN  
tcp6       0      0 :::111                  :::\*                    LISTEN  
tcp6       0      0 :::22                   :::\*                    LISTEN  
tcp6       0      0 :::57879                :::\*                    LISTEN  
tcp6       0      0 :::5000                 :::\*                    LISTEN  

==> cd: PLAY [localhost] *************************************************************\* 
==> cd: 
==> cd: GATHERING FACTS **************************************************************\* 
==> cd: ok: [localhost]
==> cd: 
==> cd: TASK: [java | Package are present] *******************************************\* 
==> cd: ok: [localhost] => (item=packages) => {"changed": false, "item": "packages"}
==> cd: 
==> cd: TASK: [docker | Add Docker repository and update apt cache] ******************\* 
==> cd: ok: [localhost] => {"changed": false, "repo": "deb https://apt.dockerproject.org/repo ubuntu-trusty main", "state": "present"}
==> cd: 
==> cd: TASK: [docker | Old Docker is absent] ****************************************\* 
==> cd: ok: [localhost] => {"changed": false}
==> cd: 
==> cd: TASK: [docker | Docker is present] *******************************************\* 
==> cd: ok: [localhost] => {"changed": false}
==> cd: 
==> cd: TASK: [docker | Python-pip is present] ***************************************\* 
==> cd: ok: [localhost] => {"changed": false}
==> cd: 
==> cd: TASK: [docker | Docker-py is present] ****************************************\* 
==> cd: ok: [localhost] => {"changed": false, "cmd": "/usr/bin/pip install docker-py==0.4.0", "name": "docker-py", "requirements": null, "state": "present", "stderr": "", "stdout": "Requirement already satisfied (use --upgrade to upgrade): docker-py==0.4.0 in /usr/local/lib/python2.7/dist-packages\nRequirement already satisfied (use --upgrade to upgrade): requests==2.2.1 in /usr/lib/python2.7/dist-packages (from docker-py==0.4.0)\nRequirement already satisfied (use --upgrade to upgrade): six>=1.3.0 in /usr/lib/python2.7/dist-packages (from docker-py==0.4.0)\nRequirement already satisfied (use --upgrade to upgrade): websocket-client==0.11.0 in /usr/local/lib/python2.7/dist-packages (from docker-py==0.4.0)\nRequirement already satisfied (use --upgrade to upgrade): mock==1.0.1 in /usr/local/lib/python2.7/dist-packages (from docker-py==0.4.0)\nRequirement already satisfied (use --upgrade to upgrade): coverage==3.7.1 in /usr/local/lib/python2.7/dist-packages (from docker-py==0.4.0)\nCleaning up...\n", "version": "0.4.0", "virtualenv": null}
==> cd: 
==> cd: TASK: [docker | Files are present] *******************************************\* 
==> cd: ok: [localhost] => {"changed": false, "checksum": "326f2e9dcc9b5fd0b2baae05315dbd9d7f4a36a1", "dest": "/etc/default/docker", "gid": 0, "group": "root", "mode": "0644", "owner": "root", "path": "/etc/default/docker", "size": 65, "state": "file", "uid": 0}
==> cd: 
==> cd: TASK: [docker | Docker service is restarted] *********************************\* 
==> cd: skipping: [localhost]
==> cd: 
==> cd: TASK: [registry | Directory is present] **************************************\* 
==> cd: ok: [localhost] => {"changed": false, "gid": 0, "group": "root", "mode": "0755", "owner": "root", "path": "/data/registry", "size": 4096, "state": "directory", "uid": 0}
==> cd: 
==> cd: TASK: [registry | Container is running] **************************************\* 
==> cd: changed: [localhost] => {"ansible_facts": {"docker_containers": [{"Id": "51d2ffe25cca902ed1d278bc987261068d521ba7443f103672c37dbf8a60b152", "Warnings": null}]}, "changed": true, "containers": [{"Id": "51d2ffe25cca902ed1d278bc987261068d521ba7443f103672c37dbf8a60b152", "Warnings": null}], "msg": "removed 1 container, started 1 container, created 1 container.", "reload_reasons": null, "summary": {"created": 1, "killed": 0, "pulled": 0, "removed": 1, "restarted": 0, "started": 1, "stopped": 0}}
==> cd: 
==> cd: TASK: [jenkins | Directories are present] ************************************\* 
==> cd: ok: [localhost] => (item=/data/jenkins/plugins) => {"changed": false, "gid": 0, "group": "root", "item": "/data/jenkins/plugins", "mode": "0777", "owner": "root", "path": "/data/jenkins/plugins", "size": 4096, "state": "directory", "uid": 0}
==> cd: ok: [localhost] => (item=/data/jenkins/slaves/cd) => {"changed": false, "gid": 0, "group": "root", "item": "/data/jenkins/slaves/cd", "mode": "0777", "owner": "root", "path": "/data/jenkins/slaves/cd", "size": 4096, "state": "directory", "uid": 0}
==> cd: ok: [localhost] => (item=/data/.ivy2) => {"changed": false, "gid": 0, "group": "root", "item": "/data/.ivy2", "mode": "0777", "owner": "root", "path": "/data/.ivy2", "size": 4096, "state": "directory", "uid": 0}
==> cd: 
==> cd: TASK: 
==> cd: [jenkins | Config files are present] ***********************************\* 
==> cd: ok: [localhost] => (item=config.xml) => {"changed": false, "checksum": "6e659b8e2881734e449e706df71bc42e0a5fc0c6", "dest": "/data/jenkins/config.xml", "gid": 0, "group": "root", "item": "config.xml", "mode": "0644", "owner": "root", "path": "/data/jenkins/config.xml", "size": 1918, "state": "file", "uid": 0}
==> cd: 
==> cd: TASK: [jenkins | Plugins are present] ****************************************\* 
==> cd: ok: [localhost] => (item=github.hpi) => {"changed": false, "checksum": "b3ca6cc353c9fb36bf47aa13306b597cf3aef41e", "dest": "/data/jenkins/plugins/github.hpi", "gid": 0, "group": "root", "item": "github.hpi", "mode": "0644", "owner": "root", "path": "/data/jenkins/plugins/github.hpi", "size": 3650640, "state": "file", "uid": 0}
==> cd: ok: [localhost] => (item=git.hpi) => {"changed": false, "checksum": "69f306f7b6aa06fba455052bbaef99530ae6058e", "dest": "/data/jenkins/plugins/git.hpi", "gid": 0, "group": "root", "item": "git.hpi", "mode": "0644", "owner": "root", "path": "/data/jenkins/plugins/git.hpi", "size": 1301966, "state": "file", "uid": 0}
==> cd: ok: [localhost] => (item=credentials.jpi) => {"changed": false, "checksum": "b44bd7cbd92cb5410f28415fbebc61d7dc21439d", "dest": "/data/jenkins/plugins/credentials.jpi", "gid": 0, "group": "root", "item": "credentials.jpi", "mode": "0644", "owner": "root", "path": "/data/jenkins/plugins/credentials.jpi", "size": 406478, "state": "file", "uid": 0}
==> cd: ok: [localhost] => (item=scm-api.hpi) => {"changed": false, "checksum": "cc98487e2daaf7484a2028f62828bf6f9ef986ce", "dest": "/data/jenkins/plugins/scm-api.hpi", "gid": 0, "group": "root", "item": "scm-api.hpi", "mode": "0644", "owner": "root", "path": "/data/jenkins/plugins/scm-api.hpi", "size": 75264, "state": "file", "uid": 0}
==> cd: ok: [localhost] => (item=matrix-project.jpi) => {"changed": false, "checksum": "deeafa20f3a597789afd0917f915bff690c14074", "dest": "/data/jenkins/plugins/matrix-project.jpi", "gid": 0, "group": "root", "item": "matrix-project.jpi", "mode": "0644", "owner": "root", "path": "/data/jenkins/plugins/matrix-project.jpi", "size": 237973, "state": "file", "uid": 0}
==> cd: ok: [localhost] => (item=git-client.hpi) => {"changed": false, "checksum": "df981521f905d0c3d2442945cf93444cf1ec02d3", "dest": "/data/jenkins/plugins/git-client.hpi", "gid": 0, "group": "root", "item": "git-client.hpi", "mode": "0644", "owner": "root", "path": "/data/jenkins/plugins/git-client.hpi", "size": 3391722, "state": "file", "uid": 0}
==> cd: ok: [localhost] => (item=github-api.hpi) => {"changed": false, "checksum": "e133a80f6f9776c38fdf0dadd328a7f0c3bca666", "dest": "/data/jenkins/plugins/github-api.hpi", "gid": 0, "group": "root", "item": "github-api.hpi", "mode": "0644", "owner": "root", "path": "/data/jenkins/plugins/github-api.hpi", "size": 3258615, "state": "file", "uid": 0}
==> cd: 
==> cd: TASK: [jenkins | Build job directories are present] **************************\* 
==> cd: ok: [localhost] => (item=books-service) => {"changed": false, "gid": 0, "group": "root", "item": "books-service", "mode": "0777", "owner": "root", "path": "/data/jenkins/jobs/books-service", "size": 4096, "state": "directory", "uid": 0}
==> cd: 
==> cd: TASK: [jenkins | Build jobs are present] *************************************\* 
==> cd: ok: [localhost] => (item=books-service) => {"changed": false, "gid": 0, "group": "root", "item": "books-service", "mode": "0777", "owner": "root", "path": "/data/jenkins/jobs/books-service/config.xml", "size": 2245, "state": "file", "uid": 0}
==> cd: 
==> cd: TASK: [jenkins | Deployment job directories are present] *********************\* 
==> cd: ok: [localhost] => (item=books-service) => {"changed": false, "gid": 0, "group": "root", "item": "books-service", "mode": "0777", "owner": "root", "path": "/data/jenkins/jobs/books-service-deployment", "size": 4096, "state": "directory", "uid": 0}
==> cd: 
==> cd: TASK: [jenkins | Deployment jobs are present] ********************************\* 
==> cd: ok: [localhost] => (item=books-service) => {"changed": false, "gid": 0, "group": "root", "item": "books-service", "mode": "0777", "owner": "root", "path": "/data/jenkins/jobs/books-service-deploymen
==> cd: t/config.xml", "size": 717, "state": "file", "uid": 0}
==> cd: 
==> cd: TASK: [jenkins | Container is running] ***************************************\* 
==> cd: changed: [localhost] => {"ansible_facts": {"docker_containers": [{"Id": "de29118f815d8b7d3053f2c6952c140d3fcbae9388ba6841f5fbac8a73ca0821", "Warnings": null}]}, "changed": true, "containers": [{"Id": "de29118f815d8b7d3053f2c6952c140d3fcbae9388ba6841f5fbac8a73ca0821", "Warnings": null}], "msg": "removed 1 container, started 1 container, created 1 container.", "reload_reasons": null, "summary": {"created": 1, "killed": 0, "pulled": 0, "removed": 1, "restarted": 0, "started": 1, "stopped": 0}}
==> cd: 
==> cd: TASK: [jenkins | Reload] *****************************************************\* 
==> cd: failed: [localhost] => {"failed": true, "parsed": false}
==> cd: BECOME-SUCCESS-txrfjbhhiiwyigwynvwdbmzqpgazeusl
==> cd: Traceback (most recent call last):
==> cd:   File "/root/.ansible/tmp/ansible-tmp-1460570008.8-171050239842331/uri", line 2067, in <module>
==> cd:     main()
==> cd:   File "/root/.ansible/tmp/ansible-tmp-1460570008.8-171050239842331/uri", line 419, in main
==> cd:     resp, content, dest = uri(module, url, dest, user, password, body, method, dict_headers, redirects, socket_timeout, validate_certs)
==> cd:   File "/root/.ansible/tmp/ansible-tmp-1460570008.8-171050239842331/uri", line 312, in uri
==> cd:     resp, content = h.request(url, method=method, body=body, headers=headers)  
==> cd:   File "/usr/lib/python2.7/dist-packages/httplib2/**init**.py", line 1569, in request
==> cd:     (response, content) = self._request(conn, authority, uri, request_uri, method, body, headers, redirections, cachekey)
==> cd:   File "/usr/lib/python2.7/dist-packages/httplib2/__init__.py", line 1316, in _request
==> cd:     (response, content) = self._conn_request(conn, request_uri, method, body, headers)
==> cd:   File "/usr/lib/python2.7/dist-packages/httplib2/__init__.py", line 1285, in _conn_request
==> cd:     response = conn.getresponse()
==> cd:   File "/usr/lib/python2.7/httplib.py", line 1051, in getresponse
==> cd:     response.begin()
==> cd:   File "/usr/lib/python2.7/httplib.py", line 415, in begin
==> cd:     version, status, reason = self._read_status()
==> cd:   File "/usr/lib/python2.7/httplib.py", line 379, in _read_status
==> cd:     raise BadStatusLine(line)
==> cd: httplib.BadStatusLine: ''
==> cd: 
==> cd: ...ignoring
==> cd: 
==> cd: PLAY RECAP *******************************************************************\* 
==> cd: localhost                  : ok=19   changed=2    unreachable=0    failed=0

**Comment by vfarcic** [comment]
I finally got some free time and checked the code. The last task (the one that failed) is not needed at all. I removed it. Please pull the latest code and the error you pasted will not appear.

As for the problem of not being able to open Jenkins, can you please try opening [http://192.168.50.91:8080](http://192.168.50.91:8080)? 192.168.50.91 is the IP of the VM Vagrant creates. If it still doesn't work, please enter the VM, display Docker processes, and check that Jenkins is indeed running.

``` bash
vagrant ssh cd

sudo docker ps -a
```

The output should be similar to the following.

```
CONTAINER ID        IMAGE               COMMAND                  CREATED             STATUS              PORTS                               NAMES
ff4573cfae10        jenkins             "/bin/tini -- /usr/lo"   7 minutes ago       Up 7 minutes        0.0.0.0:8080->8080/tcp, 50000/tcp   jenkins
028a2dda6e64        registry            "docker-registry"        8 minutes ago       Up 8 minutes        0.0.0.0:5000->5000/tcp              registry
```

**Comment by bayareahank** [comment]
It looks like Jenkins exited prematurely, here is the msg with the latest code: 

CONTAINER ID        IMAGE               COMMAND                  CREATED             STATUS                      PORTS                    NAMES
2e657f68edb4        jenkins             "/bin/tini -- /usr/lo"   39 seconds ago      Exited (1) 39 seconds ago                            jenkins
6cea2df34e12        registry            "docker-registry"        43 seconds ago      Up 42 seconds               0.0.0.0:5000->5000/tcp   registry

**Comment by vfarcic** [comment]
Can you send the logs of the container after it exists?

``` bash
docker logs jenkins
```

**Comment by bayareahank** [comment]
It looks the jenkins_home directory isn't created under /var, and Jenkins isn't installed. Here is the log: 

sudo docker logs jenkins
Can not write to /var/jenkins_home/copy_reference_file.log. Wrong volume permissions?
touch: cannot touch ‘/var/jenkins_home/copy_reference_file.log’: Permission denied

ls -l /etc/init.d/jenkins
ls: cannot access /etc/init.d/jenkins: No such file or directory

ps -ef | grep jenkins
vagrant   4605  4389  0 18:27 pts/0    00:00:00 grep --color=auto jenkins

vagrant@cd:~$ ls -l /var/
total 44
drwxr-xr-x  2 root root   4096 Apr 12 06:27 backups
drwxr-xr-x 12 root root   4096 Mar 19 06:51 cache
drwxr-xr-x  3 root root   4096 Mar 17 20:26 chef
drwxrwxrwt  2 root root   4096 Apr  9 00:28 crash
drwxr-xr-x 52 root root   4096 Apr  5 18:06 lib
drwxrwsr-x  2 root staff  4096 Apr 10  2014 local
lrwxrwxrwx  1 root root      9 Mar  4 20:42 lock -> /run/lock
drwxrwxr-x 10 root syslog 4096 Apr 14 06:44 log
drwxrwsr-x  2 root mail   4096 Mar  4 20:42 mail
drwxr-xr-x  2 root root   4096 Mar  4 20:42 opt
lrwxrwxrwx  1 root root      4 Mar  4 20:42 run -> /run
drwxr-xr-x  5 root root   4096 Mar  4 20:42 spool
drwxrwxrwt  2 root root   4096 Mar  4 20:46 tmp

vagrant@cd:~$ docker --version
Docker version 1.10.3, build 20f81dd

**Comment by vfarcic** [comment]
When you see from logs that some directory is not accessible, you should check it inside the container. For example:

``` bash
sudo docker exec -it jenkins bash

ls -l /var/jenkins_home/
```

That being said, thank you for the output. It helped me figure out what's wrong. The article is more than a year old. At the beginning, I used my own Jenkins container in that article. If I remember correctly, at that time there was no official Jenkins container. Not long ago, almost a year after the article was published, one of the readers suggested that I change it to the official version. I did the change without testing everything. Sorry for that.

Anyways, please pull the latest code and try it again. Now it should work.

Also, bear in mind that the Ansible code from that article is very old and I improved a lot the code that treats similar cases in more recent repositories and articles. Can I offer you a free copy of [The DevOps 2.0 Toolkit](http://www.amazon.com/dp/B01BJ4V66M) that, among other things, explains in much more detail Docker and Jenkins subjects? Please send me your email and I'll get back to you with a free coupon. You'll find my info in the blog's [About](https://technologyconversations.com/about/) page.

**Comment by bayareahank** [comment]
I tried with the latest code, somehow the Jenkins docker image still exited prematurely, with similar message as before: 

sudo docker ps -a 
CONTAINER ID        IMAGE               COMMAND                  CREATED             STATUS                     PORTS                    NAMES
5d973e2ce7e4        jenkins             "/bin/tini -- /usr/lo"   2 minutes ago       Exited (1) 2 minutes ago                            jenkins
944ce31a0bd0        registry            "docker-registry"        2 minutes ago       Up 2 minutes               0.0.0.0:5000->5000/tcp   registry

sudo docker logs jenkins
touch: cannot touch ‘/var/jenkins_home/copy_reference_file.log’: Permission denied
Can not write to /var/jenkins_home/copy_reference_file.log. Wrong volume permissions?

Would love to read your new book, will contact you.

**Comment by vfarcic** [comment]
Hi,

I forgot to add one thing to the previous message. You should destroy the container and remove the host directory /data/jenkins before trying it again.

``` bash
sudo docker rm -f jenkins

sudo rm -rf /data/jenkins
```

The problem is that I am not able to reproduce the same problem. That, in itself, is strange since we both use exactly the same VM and provisioning. Can we have a chat through Skype or HangOuts? If I can see your screen, I'm sure we'll resolve this quickly.

**Comment by bayareahank** [comment]
Hi Viktor, 

Indeed it is a directory write permission issue. 

I checked out the Jenkins docker by:  

sudo docker inspect jenkins

It shows the following mount info: 

"Mounts": [
            {
                "Source": "/data/jenkins",
                "Destination": "/var/jenkins_home",
                "Mode": "rw",
                "RW": true,
                "Propagation": "rprivate"
            }
        ],

I tried start jenkins docker manually, it returns the same permission denied error. When I checked the /data/jenkins_home directory, it has the following permission: 

drwxr-xr-x 5 root root 4096 Apr 15 16:43 jenkins

I then chmod a+w jenkins, then the docker image starts fine, so finally it is listening on 8080. 

So I assume this is some script setting issue, on the /data/jenkins directory, before docker starts. FYI.

**Comment by vfarcic** [comment]
That's very strange since the last update I made to the code changes all permissions to 777. I know it's not a good practice but it should be a quick fix to the problem you're experiencing. If you take a look at [ansible/roles/jenkins/tasks/main.yml](https://github.com/vfarcic/jenkins-docker-ansible/blob/master/ansible/roles/jenkins/tasks/main.yml) you'll see that every time a directory is created, it is done with the mode "0777". Did you pull the code and removed everything before the last attempt you made?

**Comment by bayareahank** [comment]
Destroyed the vms and rebuild everything again, Jenkins docker starts normally this time. I would consider this issue solved. 

Thank you, Viktor.
